[build]
  command = "go run github.com/ButterCMS/hugo-starter-buttercms/prebuild && hugo"

[build.environment]
  GO_VERSION = "1.18"

[template.environment]
BUTTERCMS_API_TOKEN = "b362c2f0d01fd310d1bca1ff9ce1160a2f0deb0e"
BUTTERCMS_PREVIEW = "true"

[template.build]
  command = "go run github.com/ButterCMS/hugo-starter-buttercms/prebuild && hugo"
